name: Validate CloudFormation Template

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    
    - name: Validate CloudFormation template
      run: |
        aws cloudformation validate-template \
          --template-body file://lightsail-wordpress.yaml
    
    - name: Lint shell scripts
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
        shellcheck scripts/*.sh || true
    
    - name: Check YAML syntax
      run: |
        sudo apt-get install -y yamllint
        yamllint lightsail-wordpress.yaml || true
